# Generated by Django 5.1.3 on 2025-01-12 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(help_text='Name of the group', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='WhatsApp template name', max_length=255)),
                ('language', models.CharField(default='en_US', help_text='Language code, e.g., en_US', max_length=10)),
                ('category', models.CharField(choices=[('UTILITY', 'UTILITY'), ('MARKETING', 'MARKETING'), ('AUTHENTICATION', 'AUTHENTICATION')], help_text='Template category', max_length=15)),
                ('template_type', models.CharField(choices=[('STANDARD', 'Standard'), ('MEDIA', 'Media')], default='Standard', max_length=20)),
                ('body', models.TextField(help_text='Template body with placeholders like {{1}}, {{2}}')),
                ('headerType', models.CharField(default='None', max_length=20)),
                ('header', models.CharField(blank=True, help_text='Optional header text', max_length=255, null=True)),
                ('header_media', models.FileField(blank=True, null=True, upload_to='media')),
                ('footer', models.CharField(blank=True, help_text='Optional footer text', max_length=255, null=True)),
                ('button1', models.JSONField(blank=True, null=True)),
                ('button2', models.JSONField(blank=True, null=True)),
                ('button3', models.JSONField(blank=True, null=True)),
                ('button4', models.JSONField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False, help_text='WhatsApp template approval status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person', max_length=200)),
                ('phone', models.CharField(max_length=16)),
                ('contact_group', models.ForeignKey(help_text='Choose the group to add contact', on_delete=django.db.models.deletion.CASCADE, to='account.contactgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the campaign', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the campaign', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='Running', max_length=15)),
                ('scheduled_time', models.DateTimeField(blank=True, help_text='Scheduled time to start the campaign', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('to_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.contactgroup')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='account.template')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(help_text="Recipient's WhatsApp phone number", max_length=20)),
                ('recipient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('response_id', models.CharField(blank=True, help_text='Message ID returned by WhatsApp API', max_length=255, null=True)),
                ('response_text', models.TextField(blank=True, help_text='API response or error details', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='account.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.userrole'),
        ),
    ]
