# Generated by Django 5.1.3 on 2025-01-20 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='campaign_limit',
            field=models.IntegerField(default=1, help_text='Limit of creating campaigns'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='messages_limit',
            field=models.IntegerField(default=1, help_text='Limit of sending messages'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='subscriptions.subscription'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='template_limit',
            field=models.IntegerField(default=1, help_text='Limit of template creation'),
        ),
    ]
