# Generated by Django 5.1.3 on 2025-01-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_campaign_limit_customuser_messages_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='budget',
            field=models.IntegerField(default=100),
        ),
    ]
