# Generated by Django 5.1.3 on 2025-02-12 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_campaign_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='from_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='account.campaign'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient_phone',
            field=models.CharField(blank=True, help_text="Recipient's WhatsApp phone number", max_length=20),
        ),
    ]
