# Generated by Django 5.1.3 on 2025-02-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_accesstoken_message_from_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialsManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gupshup_appId', models.CharField(max_length=200)),
                ('gupshup_token', models.CharField(max_length=200)),
            ],
        ),
    ]
