# Generated by Django 5.1.3 on 2025-01-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('template_limit', models.IntegerField(help_text='Limit of template creation')),
                ('campaign_limit', models.IntegerField(help_text='Limit of creating campaigns')),
                ('messages_limit', models.IntegerField(help_text='Limit of sending messages')),
                ('features', models.TextField()),
            ],
        ),
    ]
